### ISSUE TITLE
Readme references broken link

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/react-prop-types#5]
The link to https://facebook.github.io/react/docs/reusable-components.html#prop-validation redirects to a much more generic and basically useless resource on react components & props that doesn't reference validation. 

The link appears twice in the readme.

**Comment by edmundo096** [comment]
I can confirm it.
Also, now `PropTypes` is deprecated and was moved to https://facebook.github.io/react/docs/typechecking-with-proptypes.html

Seems that they extracted the validation out of the React core to a development-only module/library.

**Comment by Lukeghenco** [comment]
Thanks @walwoodr & @edmundo096 just fixed this with a PR

**Comment by itzsaga** [comment]
Hey @Lukeghenco, the resources link was updated but not the two links that are inline in the readme.

**Comment by edmundo096** [comment]
Yeah, @itzsaga  you are right. Need to check @Lukeghenco the other page links, I think there are still 2 references on the Readme that need to be updated.
